version: "3.9"

services:
  db:
    image: postgres:16
    container_name: vrisa_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vrisa_db
    ports:
      - "5432:5432"
    volumes:
      - vrisa_data:/var/lib/postgresql/data
    
  pgadmin:
    image: dpage/pgadmin4
    container_name: vrisa_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@vrisa.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  backend:
    build: .
    container_name: vrisa_backend
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - .:/app
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: vrisa_db
      JWT_SECRET: super_secret_key
      JWT_EXPIRES: 7d
    depends_on:
      - db

volumes:
  vrisa_data:
